[project]
name = "budget-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.8",
    "dotenv>=0.9.9",
    "mysqlclient>=2.2.7",
    "openai>=2.8.1",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
]
